"
I know how to lookup class and global variables.
"
Class {
	#name : 'ASEnclosingScope',
	#superclass : 'Object',
	#category : 'ASTSmalltalk-CodeGen',
	#package : 'ASTSmalltalk',
	#tag : 'CodeGen'
}

{ #category : 'compiling' }
ASEnclosingScope >> find: aSymbol [
"This must be a class variable or global"
]

{ #category : 'compiling' }
ASEnclosingScope >> lookupName: anObject block: blockOther [

	"self error: 'Cannot find '"
]
