Class {
	#name : 'ZagTestConstants',
	#superclass : 'SharedPool',
	#classVars : [
		'T1',
		'T2',
		'T3',
		'T4',
		'T5'
	],
	#classInstVars : [
		'p1',
		'p2',
		'p3',
		'p4',
		'p5'
	],
	#category : 'Zag-Exporter-Tests-Explore',
	#package : 'Zag-Exporter-Tests',
	#tag : 'Explore'
}

{ #category : 'class initialization' }
ZagTestConstants class >> initialize [

	T1 := 1.
	T2 := 2.
	T3 := 3.
	T4 := 4.
	T5 := 5.
	p1 := 1.
	p2 := 2.
	p3 := 3.
	p4 := 4.
	p5 := 5
]

{ #category : 'class initialization' }
ZagTestConstants class >> p1 [

	^ p1
]

{ #category : 'class initialization' }
ZagTestConstants class >> p2 [

	^ p2
]

{ #category : 'class initialization' }
ZagTestConstants class >> p3 [

	^ p3
]

{ #category : 'class initialization' }
ZagTestConstants class >> p4 [

	^ p4
]

{ #category : 'class initialization' }
ZagTestConstants class >> p5 [

	^ p5
]

{ #category : 'class initialization' }
ZagTestConstants class >> t1 [

	^ 1
]

{ #category : 'class initialization' }
ZagTestConstants class >> t2 [

	^ 2
]

{ #category : 'class initialization' }
ZagTestConstants class >> t3 [

	^ 3
]

{ #category : 'class initialization' }
ZagTestConstants class >> t4 [

	^ 4
]

{ #category : 'class initialization' }
ZagTestConstants class >> t5 [

	^ 5
]
