Class {
	#name : #ASZigWriteStreamTest,
	#superclass : #TestCase,
	#category : #'ASTSmalltalk-Tests-Tests'
}

{ #category : #tests }
ASZigWriteStreamTest >> testPushLiteral [
	"comment stating purpose of instance-side method"

	"scope: class-variables  &  instance-variables"

	| temporary variable names statements |
	statements
]

{ #category : #tests }
ASZigWriteStreamTest >> testPushLocal [
	"comment stating purpose of instance-side method"

	"scope: class-variables  &  instance-variables"

	| temporary variable names statements |
	statements
]
