#! /bin/sh
if test -d ~/Documents/Pharo; then
    pharo=$HOME/Documents/Pharo
    vm=`ls -tr $pharo/vms/$1*/Pharo.app/Contents/MacOS/Pharo 2>/dev/null|tail -1`
elif test -d ~/Pharo; then
    pharo=$HOME/Pharo
    vm=`ls -tr $pharo/vms/$1*/pharo 2>/dev/null|tail -1`
fi
case "$vm" in
    '') echo 'Pharo vm not found where expected' >&2
        exit 1;;
esac

image=`ls -tr $pharo/images/*/*.image 2>/dev/null|tail -1`
cat <<EOF | $vm $image eval "ZagImageEncoder initializeFromStdin"
Zag
validInitialization true
comment 'timestamp...'
EOF
