name: Fib Benchmark

on:
  push:
    branches:
      - main
      - docs-actions
  workflow_dispatch:

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    name: bench (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build and run fib bench (all encodings)
        run: zig build bench -Doptimize=ReleaseFast -Dtarget=x86_64-linux-gnu -Dcpu=baseline -j1 --summary all
        working-directory: zig
